spring:
  application:
    name: training-session-management

server:
  port: 8766

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/

application:
  security:
    jwt:
      secret-key: "48656c6c6f2c2068656c6c6f206d79206e616d65206973204967726973303034"
